### PR TITLE
Update TUTORIAL.md

### PR DESCRIPTION
**Pull request by emilebosch**
TLDR'ing the rules for easy use :) I don't agree with number 17 because it doesn't model the business. We don't say. Hey Jim can you oderDelete that for me? We say, delete that order. But apart from that all is cool.

### CODE REVIEW

**Comment by eapache** [comment]
Good idea!
- you missed number 7
- I wouldn't mind some sort of intro sentence guiding people to read the whole thing for context, since the rules on their own tend to need some explanation? Or maybe this TLDR should just go at the end of the guide instead of the beginning?

**Comment by emilebosch** [comment]
@eapache I've moved the TLDR to the bottom and added number 7. I don't know about the introduction text because I can't think of a sentence that adds any value except being more aesthetically pleasing.

**Comment by eapache** [comment]
Thanks!

**Comment by chrisbutcher** [comment]
Thank you! 🎉

**Pull request merged**
